USE [master]
GO
/****** Object:  Database [SoftCrylicDB]    Script Date: 30-11-2022 12:16:56 PM ******/
CREATE DATABASE [SoftCrylicDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SoftCrylicDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SoftCrylicDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SoftCrylicDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SoftCrylicDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SoftCrylicDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SoftCrylicDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SoftCrylicDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SoftCrylicDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SoftCrylicDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SoftCrylicDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SoftCrylicDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET RECOVERY FULL 
GO
ALTER DATABASE [SoftCrylicDB] SET  MULTI_USER 
GO
ALTER DATABASE [SoftCrylicDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SoftCrylicDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SoftCrylicDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SoftCrylicDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SoftCrylicDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SoftCrylicDB] SET QUERY_STORE = OFF
GO
USE [SoftCrylicDB]
GO
/****** Object:  Table [dbo].[EventManager]    Script Date: 30-11-2022 12:17:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EventManager](
	[EventTitle] [varchar](50) NULL,
	[EventDate] [date] NULL,
	[EventMode] [varchar](50) NULL,
	[EventVenue] [varchar](50) NULL,
	[EventSite] [varchar](max) NULL,
	[EventLink] [varchar](max) NULL,
	[SpeakerId] [int] NULL,
	[EventId] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SpeakerDetails]    Script Date: 30-11-2022 12:17:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SpeakerDetails](
	[SpeakerId] [int] NULL,
	[SpeakerName] [varchar](255) NULL,
	[SpeakerBio] [varchar](255) NULL,
	[SpeakerWeb] [varchar](255) NULL,
	[SpeakerSession] [int] NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [SoftCrylicDB] SET  READ_WRITE 
GO